### ISSUE TITLE
Completes without running diamond,pocp,pocp matrix task.

### ISSUE THREAD

**Issue by APrabhu21** [hoelzer/pocp#21]
Hello, I'm trying to calculate the pocp of of 24 genomes using your tool in all-vs-all fashion.
I have both nucleotide and protein fasta files of the same. I have tried with both --genomes and --proteins flags.
In case of proteins flag, the pipeline exits without doing anything and in case of genomes flag the pipeline run prokka only on the first genome and exits.
Please guide me on the same.
I have done installation through conda, version 2.3.0, profile local,conda.
I'm attaching a nextflow log for the same.
[nextflow.log.9.txt](https://github.com/user-attachments/files/15782825/nextflow.log.9.txt)

**Comment by hoelzer** [comment]
hey @APrabhu21 thx for your interest in the pipeline!

It seems you started the pipeline only using one genome FASTA as input:

```bash
nextflow run hoelzer/pocp -r 2.3.0 --genomes Alkalispirillum_mobile_strain_DSM_12769T.fasta
```

Please see [Execution examples](https://github.com/hoelzer/pocp?tab=readme-ov-file#run)

You have to use single ticks like that:

```bash
nextflow run hoelzer/pocp -r 2.3.0 --genomes '*.fasta'
```

Please dont use double ticks `"*.fasta"`.

The reason is, that your bash shell will interpret something like `"*.fasta"` as `1.fasta 2.fasta 3.fasta` but then nextflow will only run on the first file. With the single ticks, the whole list is given to nextflow and then interpreted. 

Let me know if that was the problem!

**Comment by APrabhu21** [comment]
Hello, the missing single quotes were indeed the problem.
Thank you for your prompt reply. 
Its running perfectly now.
